image: node:latest
stages:
  - test
  - build
  - run

Test:
  stage: test
  script:
    - npm install
    - npm run test

Build:
  stage: build
  script:
    - docker-compose -f docker/docker-compose.yml build
  tags:
    - mrtolerant

Run:
  stage: run
  script:
    - docker-compose -f docker/docker-compose.yml run
  tags:
    - mrtolerant