stages:
  - test
  - build
  - run

Test:
  stage: test
  image: node:v12.13.0
  script:
    - yarn install
    - yarn run test
  tags:
    - docker

Build:
  stage: build
  script:
    - docker-compose -f docker/docker-compose.yml build
  tags:
    - bash

Run:
  stage: run
  script:
    - docker-compose -f docker/docker-compose.yml run
  tags:
    - bash