stages:
  - test
  - build
  - run

Test:
  stage: test
  image: node:latest
  script:
    - yarn install
    - yarn run test
  tags:
    - docker
  only:
    - merge_requests

Build:
  stage: build
  script:
    - docker-compose -f docker/docker-compose.yml build
  tags:
    - bash

Run:
  stage: run
  script:
    - docker-compose -f docker/docker-compose.yml up -d --remove-orphans #--force-recreate
  tags:
    - bash