variables:
    SITE_HOSTNAME: mrtolerant.ru

stages:
  - build
  - test
  - run

Build:
  stage: build
  script:
    - docker-compose -f docker/docker-compose.yml build
  tags:
    - bash

Test:
  stage: test
  script:
    - docker run  --entrypoint=/bin/sh docker_node -c 'yarn test'
    - docker stop node
  tags:
    - bash
  # only:
  #   - merge_requests

Run:
  stage: run
  script:
    - docker-compose -f docker/docker-compose.yml up -d  #--force-recreate
    # - docker exec -d docker_node "yarn start"
  tags:
    - bash