variables:
    SITE_HOSTNAME: mrtolerant.ru

stages:
  - build
  - test
  - run

Build:
  stage: build
  script:
    - docker-compose -f docker/docker-compose.yml build
  tags:
    - bash

Test:
  stage: test
  script:
    - docker run  --entrypoint=/bin/sh docker_node -c 'yarn test'
    # - docker kill node
  tags:
    - bash
  # only:
  #   - merge_requests

Run:
  stage: run
  script:
    docker-compose -f docker/docker-compose.yml up -d
  tags:
    - bash