variables:
    REVIEW_HOST: ${CI_COMMIT_REF_SLUG}.${PROJECT_PREFIX}
    DOCKER_NODE: TEST_mrtolerantru_node
stages:
  - test
  - build
  - run
  - prod

Test:
  stage: test
  script:
    - docker-compose -f docker/docker-compose.yml build
    - docker-compose -f docker/docker-compose.yml run "yarn test"
    - docker-compose -f docker/docker-compose.yml down -rmi all

  tags:
    - bash
  # only:
  #   - merge_requests

Build:
  stage: build
  script:
    - docker-compose -f docker/docker-compose.yml -p ${CI_COMMIT_REF_SLUG}_${PROJECT_PREFIX} build
  tags:
    - bash
  only:
    - develop
    - master

Run:
  stage: run
  script:
    docker-compose -f docker/docker-compose.yml -p ${CI_COMMIT_REF_SLUG}_${PROJECT_PREFIX}  up -d
  tags:
    - bash
  only:
    - develop
    - master

Prod:
  stage: prod
  script:
    docker-compose -f docker/docker-compose-production.yml -p ${CI_COMMIT_REF_SLUG}  up -d --build 
  tags:
    - bash
  only:
    - production