variables:
    SITE_HOSTNAME: mrtolerant.ru

stages:
  - build
  - test 
  - run

Build:
  stage: build
  script:
    - docker-compose -f docker/docker-compose.yml build
  tags:
    - bash
  
Test:
  stage: test
  script:
    - docker run  --entrypoint '/bin/sh' node -c 'yarn && yarn test' 
    - docker-compose -f docker/docker-compose.yml down
  tags:
    - bash
  # only:
  #   - merge_requests



Run:
  stage: run
  script:
    - docker-compose -f docker/docker-compose.yml up -d --remove-orphans #--force-recreate
  tags:
    - bash