variables:
    REVIEW_HOST: ${PROJECT_PREFIX}
    PROJECT_PREFIX: url.mrtolerant.ru

stages:
  - run

Build&Run:
  stage: run
  script:
    - docker-compose -f docker/docker-compose.yml -p ${CI_COMMIT_REF_SLUG}_${PROJECT_PREFIX}  up -d --build
  tags:
    - vps
  only:
    - master
