stages:
  - build
  - test
  - run
  - prod

Build:
  stage: build
  script:
    - echo ${PROJECT_PREFIX}
    - echo ${CI_COMMIT_REF_SLUG}
    - docker-compose -f docker/docker-compose.yml -p ${CI_COMMIT_REF_SLUG}_${PROJECT_PREFIX} build
  tags:
    - bash
  only:
    - develop
    - master

# Test:
#   stage: test
#   script:
#     - docker run  --entrypoint=/bin/sh docker_node -c 'yarn test'
#   tags:
#     - bash
#   only:
#     - merge_requests

Run:
  stage: run
  script:
    docker-compose -f docker/docker-compose.yml -p ${CI_COMMIT_REF_SLUG}_${PROJECT_PREFIX}  up -d
  tags:
    - bash
  only:
    - develop
    - master

Prod:
  stage: prod
  script:
    docker-compose -f docker/docker-compose-prod.yml -p ${CI_COMMIT_REF_SLUG}_${PROJECT_PREFIX}  up -d --build
  tags:
    - bash
  only:
    - production

