version: "3.7"
services:
  node:
    build:
      target: nodeServer
      context: ../
      dockerfile: docker/Dockerfile
    container_name: node
    restart: always
    networks:
      - review
    labels:
      - traefik.enable=false

  nginx:
    build:
      target: webServer
      context: ../
      dockerfile: docker/Dockerfile
    container_name: nginx
    restart: always
    networks:
      - review
    labels:
      - "traefik.docker.network=review"
      - "traefik.basic.frontend.rule=Host:mrtolerant.ru"
      - "traefik.basic.protocol=http"
    depends_on:
      - node

networks:
  review:
    external: true

