version: "3.7"
services:
  node:
    build:
      target: nodeServer
      context: ../
      dockerfile: docker/Dockerfile
    container_name: node
    restart: always
    networks:
      - review
    labels:
      - traefik.enable=false

  nginx:
    build:
      target: webServer
      context: ../
      dockerfile: docker/Dockerfile
    container_name: nginx
    restart: always
    networks:
      - review
    labels:
      - "traefik.enable=true"
      - 'traefik.frontend.rule=Host:mrtolerant.ru'
      - "traefik.port=80"
    depends_on:
      - node

networks:
  review:
    external: true

